# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest ply
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=18 --max-line-length=127 --statistics
    - name: Test 
      run: |
        
        python main.py < tests/Hello/Hello_test
        python machine.py
        pytest tests/Hello/test_hello.py

        head -c $(shuf -i 1-10000 -n 1) /dev/urandom | tr -dc '[:print:]' > input.txt
        python main.py < tests/Cat/Cat_test
        python machine.py
        pytest tests/Cat/test_cat.py::test_random_input
        
        echo -e "fshbdkjkf;navl kjsfrbilVAHBHDLFADNVJDIGBLUIEVJCvnfs43875t45yrgi" > input.txt
        python main.py < tests/Cat/Cat_test
        python machine.py
        pytest tests/Cat/test_cat.py::test_input_log

        echo -e "Alice\n" > input.txt
        python main.py < tests/Hello_user_name/Hello_user_name_test
        python machine.py
        pytest tests/Hello_user_name/test_hello_user_name.py
        
        python main.py < tests/Fibonnachi/Fibonnachi_test
        python machine.py
        pytest tests/Fibonnachi/test_fibonnachi.py

        
